---

# TODO: secure ENV

# - debug:
#     var: ansible_default_ipv6
#     # var: ansible_default_ipv4.network + '/' + ansible_default_ipv4.prefix|string
# - pause:

- name: Gather info about specific network
  containers.podman.podman_network_info:
    name: "podman"
  register: _podman_network_info
# - name: Create new firewalld zone for internal networking
#   ansible.posix.firewalld:
#     zone: internal_ldap
#     state: present
#     permanent: true
#   register: firewalld_new_zone
#   tags: firewalld

# - name: Reload firewalld after new zone creation
#   ansible.builtin.service:
#     name: firewalld
#     state: reloaded
#   when: firewalld_new_zone.changed | bool # noqa: no-handler
#   tags: firewalld

# - name: Add source network for internal network
#   ansible.posix.firewalld:
#     source: "{{ item }}"
#     # zone: internal_ldap
#     state: enabled
#     immediate: true
#     permanent: true
#   loop:
#     - "{{ ansible_default_ipv4.network + '/' + ansible_default_ipv4.prefix|string }}"
#     - "{{ _podman_network_info.networks[0].subnets[0].subnet }}"
#   tags: firewalld

# - name: Add source network for internal network - or just the mail server
#   ansible.posix.firewalld:
#     source: 2a01:4f8:210:31ae:190::25/80
#     zone: internal_ldap
#     state: enabled
#     immediate: true
#     permanent: true
#   tags: firewalld

- name: Disable port ldap 389
  ansible.posix.firewalld:
    zone: public
    service: ldap
    permanent: true
    immediate: true
    state: disabled
  tags: firewalld

- name: Open port ldaps 636
  ansible.posix.firewalld:
    zone: public
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop:
    - ldaps
    # - ssh
    # - dns
  tags: firewalld

- name: Block from external network
  ansible.posix.firewalld:
    rich_rule: rule family="ipv4" source NOT address="{{
      ansible_default_ipv4.network + '/' + ansible_default_ipv4.prefix | string }}" port port="636" protocol="tcp" reject
    zone: public
    permanent: true
    immediate: true
    state: enabled

# the next task will return:
# - _container_storage_dir_base_local
# - _container_storage_dir_base
# - _group, _owner
# - _systemd_scope
# - _systemd_service_files_dir
# - _xdg_runtime_dir
- name: Include podman_init_vars.yml from sleif.podman
  ansible.builtin.include_tasks: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files: sleif.podman/tasks/includes/podman_init_vars.yml
      paths: "{{ lookup('config', 'DEFAULT_ROLES_PATH') }}"
  tags: always

- name: Create persistant openldap data directories
  become: "{{ podman_rootless | bool }}"
  become_user: "{{ podman_user if podman_rootless | bool else omit }}"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0770'
  loop:
    # - '{{ _container_storage_dir_base }}/ldap/bootstrap-custom'
    - '{{ _container_storage_dir_base }}/ldap/certs'
    - '{{ _container_storage_dir_base }}/ldap/data'
    # - '{{ _container_storage_dir_base }}/ldap/config'
    # - '{{ _container_storage_dir_base }}/ldap/backup'

- name: Initial fill certificate directory
  become: "{{ podman_rootless | bool }}"
  become_user: "{{ podman_user if podman_rootless | bool else omit }}"
  ansible.builtin.shell: |
    podman unshare diff -q {{ certificate_src }}/{{
    ldap_host }}/{{ ldap_host }}.crt {{ _container_storage_dir_base }}/ldap/certs/{{ ldap_host }}.crt || (
    podman unshare cp -aTLv --remove-destination {{ certificate_src }}/{{ ldap_host }} {{ _container_storage_dir_base }}/ldap/certs;
    podman unshare chown -Rh {{ podman_user }}:{{ podman_group }} {{ _container_storage_dir_base }}/ldap/certs;
    podman restart {{ container_name }} > /dev/null )
  register: _result
  changed_when: _result.rc != 0
  tags: ldapcron

- name: Include role sleif.podman podman_operation pod_create
  ansible.builtin.include_role:
    name: sleif.podman
    apply:
      tags:
        - podman_pod_create
  vars:
    podman_operation: pod_create
  tags: always

- name: Pull container image bitnami/openldap
  become: "{{ podman_rootless | bool }}"
  become_user: "{{ podman_user if podman_rootless | bool else omit }}"
  containers.podman.podman_image:
    name: "docker.io/bitnami/openldap"
    tag: "{{ openldap_container_version }}"
    force: true

- name: Create Container bitnami/openldap
  become: "{{ podman_rootless | bool }}"
  become_user: "{{ podman_user if podman_rootless | bool else omit }}"
  containers.podman.podman_container:
    name: "{{ container_name }}"
    image: "docker.io/bitnami/openldap:{{ openldap_container_version }}"
    state: created
    restart_policy: always
    recreate: "{{ podman_container_recreate | d(false) }}"
    # restart: true
    published_ports:
      # - '389:389'
      - '636:636'
    stop_timeout: 90
    network: "slirp4netns:port_handler=slirp4netns"
    # network: "{{ podman_network_name }}"
    volumes:
      - '{{ _container_storage_dir_base }}/ldap/certs:/opt/bitnami/openldap/certs:Z'
      - '{{ _container_storage_dir_base }}/ldap/data:/bitnami/openldap:Z'
      # - '{{ _container_storage_dir_base }}/ldap/bootstrap-custom:/container/service/slapd/assets/config/bootstrap/ldif/custom:Z'
      # # - '{{ _container_storage_dir_base }}/ldap/certs:/container/service/slapd/assets/certs:Z'
      # - '{{ _container_storage_dir_base }}/ldap/data:/var/lib/ldap:Z'
      # - '{{ _container_storage_dir_base }}/ldap/config:/etc/ldap/slapd.d:Z'
      # - '{{ _container_storage_dir_base }}/ldap/backup:/data/backup:Z'
    # security_opts: label:type:docker_t
    env:
      # https://www.openldap.org/doc/admin24/runningslapd.html
      # https://www.openldap.org/doc/admin24/slapdconf2.html
      # consider olcLogLevel -1 setting in ldap/config/cn=config.ldif
      BITNAMI_DEBUG: true
      # LDAP_LOGLEVEL: "-1"
      # CONTAINER_LOG_LEVEL: "1024"
      LDAP_PORT_NUMBER: "389"
      LDAP_ROOT: "{{ ldap_base_dn }}"
      LDAP_ADMIN_USER: "admin"
      LDAP_ADMIN_PASSWORD: "{{ ldap_admin_password }}"
      LDAP_CONFIG_ADMIN_ENABLED: "yes"
      LDAP_CONFIG_ADMIN_USER: "admin"
      LDAP_CONFIG_ADMIN_PASSWORD: "{{ ldap_config_password }}"
      LDAP_USER_DC: "{{ ldap_user_dc | d('users') }}"
      # LDAP_USERS: "{{ ldap_readonly_user_username }}"
      LDAP_USERS: ""
      # LDAP_PASSWORDS: "{{ ldap_readonly_user_password }}"
      LDAP_PASSWORDS: ""
      LDAP_SKIP_DEFAULT_TREE: "yes"
      LDAP_ENABLE_TLS: "yes"
      # LDAP_REQUIRE_TLS: "yes"
      LDAP_LDAPS_PORT_NUMBER: "636"
      LDAP_TLS_CERT_FILE: "/opt/bitnami/openldap/certs/{{ ldap_host }}.crt"
      LDAP_TLS_KEY_FILE: "/opt/bitnami/openldap/certs/{{ ldap_host }}.key"
      LDAP_TLS_CA_FILE: "/opt/bitnami/openldap/certs/{{ ldap_host }}.crt"
      # LDAP_TLS_DH_PARAMS_FILE:
      LDAP_TLS_VERIFY_CLIENTS: "never"
      LDAP_ALLOW_ANON_BINDING: "no"
      LDAP_CONFIGURE_PPOLICY: "yes"
      LDAP_PPOLICY_HASH_CLEARTEXT: "yes"
      TZ: "Europe/Berlin"
    timezone: "Europe/Berlin"
  tags: ldap_container

- name: Include role sleif.podman podman_operation podman_generate_systemd
  ansible.builtin.include_role:
    name: sleif.podman
    apply:
      tags:
        - podman_generate_systemd
  vars:
    podman_operation: podman_generate_systemd
    target: "{{ pod_name if pod_name is defined and pod_name | length > 0 else container_name }}"
  tags: always

- name: Enable cronjob to provide letsencrypt certificates for ldap
  ansible.builtin.cron:
    name: "provide ldap certs"
    cron_file: openldap-backup-certs
    user: "{{ podman_user }}"
    job: "podman unshare diff -q {{ certificate_src }}/{{
          ldap_host }}/{{ ldap_host }}.crt {{ _container_storage_dir_base }}/ldap/certs/{{ ldap_host }}.crt || (
          podman unshare cp -aTLv --remove-destination {{ certificate_src }}/{{ ldap_host }} {{ _container_storage_dir_base }}/ldap/certs;
          podman unshare chown -Rh {{ podman_user }}:{{ podman_group }} {{ _container_storage_dir_base }}/ldap/certs;
          podman restart {{ container_name }} > /dev/null )"
    # job: "diff -q {{ _container_storage_dir_base }}/caddy/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/{{
    #        ldap_host }}/{{ ldap_host }}.crt
    #        {{ _container_storage_dir_base }}/ldap/certs/{{ ldap_host }}.crt || ( cp -aTL --remove-destination
    #        {{ _container_storage_dir_base }}/caddy/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/{{
    #        ldap_host }} {{ _container_storage_dir_base }}/ldap/certs > /dev/null;
    #        curl -o {{ _container_storage_dir_base }}/ldap/certs/chain2.pem https://letsencrypt.org/certs/lets-encrypt-r3.pem;
    #        cat {{ _container_storage_dir_base }}/ldap/certs/{{ ldap_host }}.crt >> {{ _container_storage_dir_base }}/ldap/certs/chain2.pem;
    #        podman restart {{ container_name }} )"
  tags: ldapcron

- name: Ensure cron mail go to root
  ansible.builtin.cron:
    cron_file: openldap-backup-certs
    user: "{{ podman_user }}"
    env: true
    name: "MAILTO"
    job: "root"
  tags: ldapcron

- name: Install openldap-clients
  ansible.builtin.package:
    name: openldap-clients
  tags: skipttag

- name: Add variable to ignore certificate chain
  ansible.builtin.lineinfile:
    dest: /etc/openldap/ldap.conf
    line: "TLS_REQCERT never"

- name: Install python-ldap
  ansible.builtin.package:
    name: python-ldap
  tags: skipttag

- name: Wait for ldap service
  ansible.builtin.wait_for:
    port: 636
    timeout: 60

# - name: Disable unencrypted connections
#   community.general.ldap_attr:
#     dn: cn=cn=config
#     name: olcTLSCipherSuite
#     values:
#       - "SECURE256:+SECURE128:-VERS-TLS-ALL:+VERS-TLS1.2:-RSA:-DHE-DSS:-CAMELLIA-128-CBC:-CAMELLIA-256-CBC:!NULL"
#     server_uri: ldap://localhost/
#     bind_dn: "cn=admin,cn=config"
#     bind_pw: "{{ LDAP_CONFIG_PASSWORD }}"
#   register: result
#   # failed_when: >
#   #   (result.failed == True) and
#   #   ("'desc': 'Type or value exists'" not in result.details)
#   tags:
#     - ldap_config_tls
# - ansible.builtin.debug:
#     msg: "result: {{ result }}"
#   tags:
#     - ldap_config_tls

# - name: Enable ppolicy module
#   community.general.ldap_attrs:
#     dn: cn=module{0},cn=config
#     attributes:
#       olcModuleLoad:
#         - "ppolicy"
#     server_uri: "{{ ldap_auth_config.server_uri }}"
#     bind_dn: "{{ ldap_auth_config.bind_dn }}"
#     bind_pw: "{{ ldap_auth_config.bind_pw }}"
#   register: result
#   until:
#     - not ( (result.failed | bool ) and ('Type or value exists' not in result.details) ) or not (result.failed | bool )
#   retries: 10
#   delay: 10
#   failed_when: >
#     (result.failed | bool ) and
#     ("'desc': 'Type or value exists'" not in result.details)
#   tags:
#     - ldap_config_ppolicy

# - ansible.builtin.debug: var=result
# - ansible.builtin.pause:

# - name: Enable ppolicy encrypt passwords
#   community.general.ldap_entry:
#     dn: olcOverlay={0}ppolicy,olcDatabase={1}mdb,cn=config
#     objectClass:
#       # - olcConfig
#       - olcOverlayConfig
#       - olcPPolicyConfig
#       # - top
#     attributes:
#       olcOverlay: "{0}ppolicy"
#       olcPPolicyDefault: "cn=default,ou=policies,{{ ldap_base_dn }}"
#       olcPPolicyHashCleartext: "TRUE"
#       # olcPPolicyUseLockout: FALSE
#       # # only for a consumer behind a syncrepl
#       # olcPPolicyForwardUpdates: FALSE
#     server_uri: "{{ ldap_auth_config.server_uri }}"
#     bind_dn: "{{ ldap_auth_config.bind_dn }}"
#     bind_pw: "{{ ldap_auth_config.bind_pw }}"
#   tags:
#     - ldap_config_ppolicy

- name: Ldap create dcObject
  community.general.ldap_entry:
    dn: "{{ ldap_base_dn }}"
    objectClass:
      - dcObject
      - organization
    attributes:
      o: "{{ ldap_organisation }}"
      dc: "{{ ldap_base_dn.split(',')[0] | regex_replace('^.{3}', '') }}"
    server_uri: "{{ ldap_auth_admin.server_uri }}"
    bind_dn: "{{ ldap_auth_admin.bind_dn }}"
    bind_pw: "{{ ldap_auth_admin.bind_pw }}"
  tags:
    - ldap_ou

- name: Ldap create LDAP read only user
  community.general.ldap_entry:
    dn: "{{ 'cn=' + ldap_readonly_user_username + ',' + ldap_base_dn }}"
    state: absent
    server_uri: "{{ ldap_auth_admin.server_uri }}"
    bind_dn: "{{ ldap_auth_admin.bind_dn }}"
    bind_pw: "{{ ldap_auth_admin.bind_pw }}"
  tags:
    - ldap_ou

- name: Ldap create LDAP read only user
  community.general.ldap_entry:
    dn: "{{ 'cn=' + ldap_readonly_user_username + ',' + ldap_base_dn }}"
    objectClass:
      - simpleSecurityObject
      - organizationalRole
    attributes:
      description: "LDAP read only user"
      # cn: "{{ ldap_readonly_user_username }}"
      userPassword: "{{ ldap_readonly_user_password }}"
      # userPassword: "{{ '{SSHA}' + ldap_readonly_user_password }}"
    server_uri: "{{ ldap_auth_admin.server_uri }}"
    bind_dn: "{{ ldap_auth_admin.bind_dn }}"
    bind_pw: "{{ ldap_auth_admin.bind_pw }}"
  tags:
    - ldap_ou

- name: Set up olcAccess rules
  community.general.ldap_attrs:
    dn: olcDatabase={2}mdb,cn=config
    attributes:
      olcAccess:
        - >-
          to attrs=userPassword,shadowLastChange
          by self write
          by dn="{{ ldap_auth_admin.bind_dn }}" write
          by anonymous auth
          by * none
        - >-
          to *
          by self read
          by dn="{{ ldap_auth_admin.bind_dn }}" write
          by dn="{{ ldap_bind_dn }}" read
          by * none
    ordered: true
    state: exact
    server_uri: "{{ ldap_auth_config.server_uri }}"
    bind_dn: "{{ ldap_auth_config.bind_dn }}"
    bind_pw: "{{ ldap_auth_config.bind_pw }}"
  tags:
    - ldap_config_access

- name: Ldap create domain ou ou={{ site_domain_ou }}
  community.general.ldap_entry:
    dn: ou={{ site_domain_ou }},{{ ldap_base_dn }}
    objectClass: organizationalUnit
    server_uri: "{{ ldap_auth_admin.server_uri }}"
    bind_dn: "{{ ldap_auth_admin.bind_dn }}"
    bind_pw: "{{ ldap_auth_admin.bind_pw }}"
  tags:
    - ldap_ou

- name: Ldap create group of unique names ou ou={{ ldap_ou_goun }}
  community.general.ldap_entry:
    dn: ou={{ ldap_ou_goun }},{{ ldap_base_dn }}
    objectClass: organizationalUnit
    server_uri: "{{ ldap_auth_admin.server_uri }}"
    bind_dn: "{{ ldap_auth_admin.bind_dn }}"
    bind_pw: "{{ ldap_auth_admin.bind_pw }}"
  tags:
    - ldap_goun

- name: Ldap create users und groups ou in ou={{ site_domain_ou }}
  community.general.ldap_entry:
    dn: ou={{ item }},ou={{ site_domain_ou }},{{ ldap_base_dn }}
    objectClass: organizationalUnit
    server_uri: "{{ ldap_auth_admin.server_uri }}"
    bind_dn: "{{ ldap_auth_admin.bind_dn }}"
    bind_pw: "{{ ldap_auth_admin.bind_pw }}"
  with_items:
    - "{{ ldap_ou_users }}"
    - "{{ ldap_ou_groups }}"
  tags:
    - ldap_ou

- name: Create groups
  community.general.ldap_entry:
    dn: cn={{ item.key }},ou={{ ldap_ou_groups }},ou={{ site_domain_ou }},{{ ldap_base_dn }}
    objectClass: posixGroup
    attributes:
      gidNumber: "{{ item.value.gid }}"
    server_uri: "{{ ldap_auth_admin.server_uri }}"
    bind_dn: "{{ ldap_auth_admin.bind_dn }}"
    bind_pw: "{{ ldap_auth_admin.bind_pw }}"
  with_dict: "{{ site_posix_groups }}"
  tags:
    - ldap_groups

# - name: Calculate user password hashes
#  ansible.builtin.shell: "echo -n '{{ item.value.password }}' | openssl dgst -sha256 -binary | openssl enc -base64"
#  register: hashes
#  with_dict: "{{ site_posix_users }}"
#  #when: emailusers is defined
#  #no_log: true
#  tags:
#    - configuration
#
# - name: Create the users
#  community.general.ldap_entry:
#    dn: cn={{item.0.key}},ou={{ ldap_ou_users }},{{ ldap_base_dn }}
#    objectClass:
#      - inetOrgPerson
#      - posixAccount
#      - top
#    attributes:
#      gidNumber: "{{item.0.value.uid}}"
#      givenName: "{{item.0.value.givenname}}"
#      homeDirectory: "/home/{{item.0.key}}"
#      loginShell: /bin/bash
#      mail: "{{item.0.value.mail}}"
#      #userPassword: "{SHA512-CRYPT}{{item.value.password}}"
#      #userPassword: "{sha512}{{item.value.password | password_hash('sha512')}}"
#      userPassword: "{sha512}{{ item.1.stdout }}"
#      sn: "{sha512}{{item.0.value.password}}"
##      sn: "{{item.value.sn}}"
#      uidNumber: "{{item.0.value.uid}}"
#      uid: "{{item.0.key}}"
#    server_uri: "{{ ldap_auth_admin.server_uri }}"
#    bind_dn: "{{ ldap_auth_admin.bind_dn }}"
#    bind_pw: "{{ ldap_auth_admin.bind_pw }}"
#  with_together:
#     - "{{ site_posix_users }}"
#     - "{{ hashes }}"
#  tags: skipttag

- name: Create the users
  community.general.ldap_entry:
    dn: cn={{ item.key }},ou={{ ldap_ou_users }},ou={{ site_domain_ou }},{{ ldap_base_dn }}
    objectClass:
      - inetOrgPerson
      - posixAccount
      - top
    attributes:
      displayName: "{{ item.value.displayName }}"
      gidNumber: "{{ item.value.gid }}"
      givenName: "{{ item.value.givenname }}"
      homeDirectory: "/home/{{ item.key }}"
      loginShell: /bin/bash
      mail: "{{ item.value.mail }}"
      # userPassword: "{SHA512-CRYPT}{{item.value.password}}"
      # userPassword: "{sha512}{{item.value.password | password_hash('sha512')}}"
      # userPassword: "{sha512}{{ item.value.password }}"
      userPassword: "{{ item.value.password }}"
      sn: "{{ item.value.sn }}"
      uidNumber: "{{ item.value.uid }}"
      uid: "{{ item.key }}"
    server_uri: "{{ ldap_auth_admin.server_uri }}"
    bind_dn: "{{ ldap_auth_admin.bind_dn }}"
    bind_pw: "{{ ldap_auth_admin.bind_pw }}"
  with_dict: "{{ site_posix_users }}"
  tags:
    - ldap_user

- name: Update members of  posix groups
  community.general.ldap_attrs:
    dn: cn={{ item.1 }},ou={{ ldap_ou_groups }},ou={{ site_domain_ou }},{{ ldap_base_dn }}
    attributes:
      memberUid:
        - "{{ item.0.name }}"
    server_uri: "{{ ldap_auth_admin.server_uri }}"
    bind_dn: "{{ ldap_auth_admin.bind_dn }}"
    bind_pw: "{{ ldap_auth_admin.bind_pw }}"
  with_subelements:
    - "{{ site_posix_users }}"
    - groups
  tags:
    - ldap_member

- name: Make sure group nextcloud exists
  community.general.ldap_entry:
    dn: cn=nextcloud,ou={{ ldap_ou_goun }},{{ ldap_base_dn }}
    objectClass:
      - groupOfUniqueNames
    attributes:
      uniqueMember:
        - "cn=dummy,ou={{ ldap_ou_users }},ou={{ site_domain_ou }},{{ ldap_base_dn }}"
    server_uri: "{{ ldap_auth_admin.server_uri }}"
    bind_dn: "{{ ldap_auth_admin.bind_dn }}"
    bind_pw: "{{ ldap_auth_admin.bind_pw }}"
  tags:
    - ldap_goun

- name: Update members of  group nextcloud
  community.general.ldap_attrs:
    dn: cn=nextcloud,ou={{ ldap_ou_goun }},{{ ldap_base_dn }}
    attributes:
      uniqueMember:
        - "cn={{ item }},ou={{ ldap_ou_users }},ou={{ site_domain_ou }},{{ ldap_base_dn }}"
    server_uri: "{{ ldap_auth_admin.server_uri }}"
    bind_dn: "{{ ldap_auth_admin.bind_dn }}"
    bind_pw: "{{ ldap_auth_admin.bind_pw }}"
  with_items: "{{ site_goun_nextcloud_users }}"
  tags:
    - ldap_goun

- name: Remove dummy member from group nextcloud
  community.general.ldap_attrs:
    dn: cn=nextcloud,ou={{ ldap_ou_goun }},{{ ldap_base_dn }}
    attributes:
      uniqueMember:
        - "cn=dummy,ou={{ ldap_ou_users }},ou={{ site_domain_ou }},{{ ldap_base_dn }}"
    state: absent
    server_uri: "{{ ldap_auth_admin.server_uri }}"
    bind_dn: "{{ ldap_auth_admin.bind_dn }}"
    bind_pw: "{{ ldap_auth_admin.bind_pw }}"
  tags:
    - ldap_goun
