---

# TODO: ldap hostname in /etc/hosts file

# - debug:
#     var: ansible_default_ipv6
#     # var: ansible_default_ipv4.network + '/' + ansible_default_ipv4.prefix|string
# - pause:

- name: Gather info about specific network
  containers.podman.podman_network_info:
    name: "podman"
  register: _podman_network_info

# - name: Create new firewalld zone for internal networking
#   ansible.posix.firewalld:
#     zone: internal_ldap
#     state: present
#     permanent: true
#   register: firewalld_new_zone
#   tags: firewalld

# - name: Reload firewalld after new zone creation
#   ansible.builtin.service:
#     name: firewalld
#     state: reloaded
#   when: firewalld_new_zone.changed | bool # noqa: no-handler
#   tags: firewalld

# - name: Add source network for internal network
#   ansible.posix.firewalld:
#     source: "{{ item }}"
#     # zone: internal_ldap
#     state: enabled
#     immediate: true
#     permanent: true
#   loop:
#     - "{{ ansible_default_ipv4.network + '/' + ansible_default_ipv4.prefix|string }}"
#     - "{{ _podman_network_info.networks[0].subnets[0].subnet }}"
#   tags: firewalld

# - name: Add source network for internal network - or just the mail server
#   ansible.posix.firewalld:
#     source: 2a01:4f8:210:31ae:190::25/80
#     zone: internal_ldap
#     state: enabled
#     immediate: true
#     permanent: true
#   tags: firewalld

- name: Disable port ldap 389
  ansible.posix.firewalld:
    # zone: internal_ldap
    service: ldap
    permanent: true
    immediate: true
    state: disabled
  tags: firewalld

- name: Open port ldaps 636
  ansible.posix.firewalld:
    # zone: internal_ldap
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop:
    - ldaps
    # - ssh
    # - dns
  tags: firewalld

- name: Create persitent ldap directory below {{ container_storage_dir_base }}
  ansible.builtin.file:
    state: directory
    path: '{{ container_storage_dir_base }}/ldap/{{ item }}'
    mode: '0750'
  with_items:
    - bootstrap-custom
  tags: skipttag

- name: Fill files for bootstrap ldap
  ansible.builtin.copy:
    src: bootstrap-custom/
    dest: '{{ container_storage_dir_base }}/ldap/bootstrap-custom'
    mode: '0640'
  tags: skipttag

- name: Create persistant openldap data directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0750'
  loop:
    - '{{ container_storage_dir_base }}/ldap/bootstrap-custom'
    - '{{ container_storage_dir_base }}/ldap/certs'
    - '{{ container_storage_dir_base }}/ldap/data'
    - '{{ container_storage_dir_base }}/ldap/config'
    - '{{ container_storage_dir_base }}/ldap/backup'

- name: Osixia-openldap-backup-Container starten
  containers.podman.podman_container:
    name: openldap_container
    # hostname: openldap-backup
    image: "docker.io/osixia/openldap-backup:{{ openldap_container_version }}"
    state: started
    restart_policy: always
    recreate: true
    # restart: true
    published_ports:
      # - '389:389'
      - '636:636'
    network: "{{ podman_network_name }}"
    volumes:
      - '{{ container_storage_dir_base }}/ldap/bootstrap-custom:/container/service/slapd/assets/config/bootstrap/ldif/custom:Z'
      - '{{ container_storage_dir_base }}/ldap/certs:/container/service/slapd/assets/certs:Z'
      - '{{ container_storage_dir_base }}/ldap/data:/var/lib/ldap:Z'
      - '{{ container_storage_dir_base }}/ldap/config:/etc/ldap/slapd.d:Z'
      - '{{ container_storage_dir_base }}/ldap/backup:/data/backup:Z'
    # security_opts: label:type:docker_t
    env:
      # https://www.openldap.org/doc/admin24/runningslapd.html
      # https://www.openldap.org/doc/admin24/slapdconf2.html
      # consider olcLogLevel -1 setting in ldap/config/cn=config.ldif
      # LDAP_LOG_LEVEL: "-1"
      # CONTAINER_LOG_LEVEL: "1024"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "false"
      LDAP_ORGANISATION: "{{ ldap_organisation }}"
      LDAP_DOMAIN: "{{ ldap_domain }}"
      LDAP_ADMIN_PASSWORD: "{{ ldap_admin_password }}"
      LDAP_CONFIG_PASSWORD: "{{ ldap_config_password }}"
      LDAP_READONLY_USER: "True"
      LDAP_READONLY_USER_USERNAME: "{{ ldap_readonly_user_username }}"
      LDAP_READONLY_USER_PASSWORD: "{{ ldap_readonly_user_password }}"
      LDAP_TLS_CRT_FILENAME: cert.pem
      LDAP_TLS_KEY_FILENAME: key.pem
      LDAP_TLS_CA_CRT_FILENAME: fullchain.pem
      LDAP_TLS_VERIFY_CLIENT: never
      LDAP_BACKUP_TTL: "90"
      # These are to automatically generate the certs
      VIRTUAL_HOST: "{{ ldap_virtual_host }}"
      LETSENCRYPT_HOST: "{{ ldap_virtual_host }}"
      LETSENCRYPT_EMAIL: "{{ ldap_letsencrypt_email }}"
  tags: ldap_container

# - name: "enable systemd service"
#   ansible.builtin.service:
#     name: "{{ (_container_start_results.podman_systemd | dict2items | list | first).key }}"
#     enabled: true

- name: Enable cronjob to provide letsencrypt certificates for ldap
  ansible.builtin.cron:
    name: "provide ldap certs"
    cron_file: openldap-backup-certs
    user: root
    job: "diff -q {{ container_storage_dir_base }}/nginx/certs/{{ ldap_virtual_host }}/cert.pem
           {{ container_storage_dir_base }}/ldap/certs/cert.pem || ( cp -auTL --remove-destination
           {{ container_storage_dir_base }}/nginx/certs/{{ ldap_virtual_host }} {{ container_storage_dir_base }}/ldap/certs > /dev/null;
           podman restart openldap-backup )"
  tags: skipttag

- name: Install openldap-clients
  ansible.builtin.package:
    name: openldap-clients
  tags: skipttag

- name: Add variable to ignore certificate chain
  ansible.builtin.lineinfile:
    dest: /etc/openldap/ldap.conf
    line: "TLS_REQCERT never"

- name: Install python-ldap
  ansible.builtin.package:
    name: python-ldap
  tags: skipttag

- name: Wait for ldap service
  ansible.builtin.wait_for:
    port: 636
    timeout: 60

# - name: Disable unencrypted connections
#   community.general.ldap_attr:
#     dn: cn=cn=config
#     name: olcTLSCipherSuite
#     values:
#       - "SECURE256:+SECURE128:-VERS-TLS-ALL:+VERS-TLS1.2:-RSA:-DHE-DSS:-CAMELLIA-128-CBC:-CAMELLIA-256-CBC:!NULL"
#     server_uri: ldap://localhost/
#     bind_dn: "cn=admin,cn=config"
#     bind_pw: "{{ LDAP_CONFIG_PASSWORD }}"
#   register: result
#   # failed_when: >
#   #   (result.failed == True) and
#   #   ("'desc': 'Type or value exists'" not in result.details)
#   tags:
#     - ldap_config_tls
# - ansible.builtin.debug:
#     msg: "result: {{ result }}"
#   tags:
#     - ldap_config_tls

- name: Enable ppolicy module
  community.general.ldap_attrs:
    dn: cn=module{0},cn=config
    attributes:
      olcModuleLoad:
        - "ppolicy"
    server_uri: "{{ ldap_auth_config.server_uri }}"
    bind_dn: "{{ ldap_auth_config.bind_dn }}"
    bind_pw: "{{ ldap_auth_config.bind_pw }}"
  register: result
  until:
    - not ( (result.failed | bool ) and ('Type or value exists' not in result.details) ) or not (result.failed | bool )
  retries: 10
  delay: 10
  failed_when: >
    (result.failed | bool ) and
    ("'desc': 'Type or value exists'" not in result.details)
  tags:
    - ldap_config_ppolicy

# - ansible.builtin.debug: var=result
# - ansible.builtin.pause:

- name: Enable ppolicy encrypt passwords
  community.general.ldap_entry:
    dn: olcOverlay={0}ppolicy,olcDatabase={1}mdb,cn=config
    objectClass:
      # - olcConfig
      - olcOverlayConfig
      - olcPPolicyConfig
      # - top
    attributes:
      olcOverlay: "{0}ppolicy"
      olcPPolicyDefault: "cn=default,ou=policies,{{ ldap_base_dn }}"
      olcPPolicyHashCleartext: "TRUE"
      # olcPPolicyUseLockout: FALSE
      # # only for a consumer behind a syncrepl
      # olcPPolicyForwardUpdates: FALSE
    server_uri: "{{ ldap_auth_config.server_uri }}"
    bind_dn: "{{ ldap_auth_config.bind_dn }}"
    bind_pw: "{{ ldap_auth_config.bind_pw }}"
  tags:
    - ldap_config_ppolicy

# - name: Enable ppolicy encrypt passwords
#   community.general.ldap_entry:
#     dn: "olcOverlay={7}ppolicy,olcDatabase={1}mdb,cn=config"
#     objectClass:
#       # - olcConfig
#       - olcOverlayConfig
#       - olcPPolicyConfig
#       # - top
#     attributes:
#       olcOverlay: "{7}ppolicy"
#       olcPPolicyDefault: "cn=default,ou=policies,{{ ldap_base_dn }}"
#       olcPPolicyHashCleartext: "TRUE"
#       # olcPPolicyUseLockout: FALSE
#       # # only for a consumer behind a syncrepl
#       # olcPPolicyForwardUpdates: FALSE
#     server_uri: ldap://localhost/
#     bind_dn: "cn=admin,cn=config"
#     bind_pw: "{{ LDAP_CONFIG_PASSWORD }}"
#     state: absent
#   tags:
#     - ldap_config_ppolicy

- name: Ldap create domain ou ou={{ site_domain_ou }}
  community.general.ldap_entry:
    dn: ou={{ site_domain_ou }},{{ ldap_base_dn }}
    objectClass: organizationalUnit
    server_uri: "{{ ldap_auth.server_uri }}"
    bind_dn: "{{ ldap_auth.bind_dn }}"
    bind_pw: "{{ ldap_auth.bind_pw }}"
  tags:
    - ldap_ou

- name: Ldap create group of unique names ou ou={{ ldap_ou_goun }}
  community.general.ldap_entry:
    dn: ou={{ ldap_ou_goun }},{{ ldap_base_dn }}
    objectClass: organizationalUnit
    server_uri: "{{ ldap_auth.server_uri }}"
    bind_dn: "{{ ldap_auth.bind_dn }}"
    bind_pw: "{{ ldap_auth.bind_pw }}"
  tags:
    - ldap_goun

- name: Ldap create users und groups ou in ou={{ site_domain_ou }}
  community.general.ldap_entry:
    dn: ou={{ item }},ou={{ site_domain_ou }},{{ ldap_base_dn }}
    objectClass: organizationalUnit
    server_uri: "{{ ldap_auth.server_uri }}"
    bind_dn: "{{ ldap_auth.bind_dn }}"
    bind_pw: "{{ ldap_auth.bind_pw }}"
  with_items:
    - "{{ ldap_ou_users }}"
    - "{{ ldap_ou_groups }}"
  tags:
    - ldap_ou

- name: Create groups
  community.general.ldap_entry:
    dn: cn={{ item.key }},ou={{ ldap_ou_groups }},ou={{ site_domain_ou }},{{ ldap_base_dn }}
    objectClass: posixGroup
    attributes:
      gidNumber: "{{ item.value.gid }}"
    server_uri: "{{ ldap_auth.server_uri }}"
    bind_dn: "{{ ldap_auth.bind_dn }}"
    bind_pw: "{{ ldap_auth.bind_pw }}"
  with_dict: "{{ site_posix_groups }}"
  tags:
    - ldap_groups

# - name: Calculate user password hashes
#  ansible.builtin.shell: "echo -n '{{ item.value.password }}' | openssl dgst -sha256 -binary | openssl enc -base64"
#  register: hashes
#  with_dict: "{{ site_posix_users }}"
#  #when: emailusers is defined
#  #no_log: true
#  tags:
#    - configuration
#
# - name: Create the users
#  community.general.ldap_entry:
#    dn: cn={{item.0.key}},ou={{ ldap_ou_users }},{{ ldap_base_dn }}
#    objectClass:
#      - inetOrgPerson
#      - posixAccount
#      - top
#    attributes:
#      gidNumber: "{{item.0.value.uid}}"
#      givenName: "{{item.0.value.givenname}}"
#      homeDirectory: "/home/{{item.0.key}}"
#      loginShell: /bin/bash
#      mail: "{{item.0.value.mail}}"
#      #userPassword: "{SHA512-CRYPT}{{item.value.password}}"
#      #userPassword: "{sha512}{{item.value.password | password_hash('sha512')}}"
#      userPassword: "{sha512}{{ item.1.stdout }}"
#      sn: "{sha512}{{item.0.value.password}}"
##      sn: "{{item.value.sn}}"
#      uidNumber: "{{item.0.value.uid}}"
#      uid: "{{item.0.key}}"
#    server_uri: "{{ ldap_auth.server_uri }}"
#    bind_dn: "{{ ldap_auth.bind_dn }}"
#    bind_pw: "{{ ldap_auth.bind_pw }}"
#  with_together:
#     - "{{ site_posix_users }}"
#     - "{{ hashes }}"
#  tags: skipttag

- name: Create the users
  community.general.ldap_entry:
    dn: cn={{ item.key }},ou={{ ldap_ou_users }},ou={{ site_domain_ou }},{{ ldap_base_dn }}
    objectClass:
      - inetOrgPerson
      - posixAccount
      - top
    attributes:
      displayName: "{{ item.value.displayName }}"
      gidNumber: "{{ item.value.gid }}"
      givenName: "{{ item.value.givenname }}"
      homeDirectory: "/home/{{ item.key }}"
      loginShell: /bin/bash
      mail: "{{ item.value.mail }}"
      # userPassword: "{SHA512-CRYPT}{{item.value.password}}"
      # userPassword: "{sha512}{{item.value.password | password_hash('sha512')}}"
      # userPassword: "{sha512}{{ item.value.password }}"
      userPassword: "{{ item.value.password }}"
      sn: "{{ item.value.sn }}"
      uidNumber: "{{ item.value.uid }}"
      uid: "{{ item.key }}"
    server_uri: "{{ ldap_auth.server_uri }}"
    bind_dn: "{{ ldap_auth.bind_dn }}"
    bind_pw: "{{ ldap_auth.bind_pw }}"
  with_dict: "{{ site_posix_users }}"
  tags:
    - ldap_user

- name: Update members of  posix groups
  community.general.ldap_attrs:
    dn: cn={{ item.1 }},ou={{ ldap_ou_groups }},ou={{ site_domain_ou }},{{ ldap_base_dn }}
    attributes:
      memberUid:
        - "{{ item.0.name }}"
    server_uri: "{{ ldap_auth.server_uri }}"
    bind_dn: "{{ ldap_auth.bind_dn }}"
    bind_pw: "{{ ldap_auth.bind_pw }}"
  with_subelements:
    - "{{ site_posix_users }}"
    - groups
  tags:
    - ldap_member

- name: Make sure group nextcloud exists
  community.general.ldap_entry:
    dn: cn=nextcloud,ou={{ ldap_ou_goun }},{{ ldap_base_dn }}
    objectClass:
      - groupOfUniqueNames
    attributes:
      uniqueMember:
        - "cn=dummy,ou={{ ldap_ou_users }},ou={{ site_domain_ou }},{{ ldap_base_dn }}"
    server_uri: "{{ ldap_auth.server_uri }}"
    bind_dn: "{{ ldap_auth.bind_dn }}"
    bind_pw: "{{ ldap_auth.bind_pw }}"
  tags:
    - ldap_goun

- name: Update members of  group nextcloud
  community.general.ldap_attrs:
    dn: cn=nextcloud,ou={{ ldap_ou_goun }},{{ ldap_base_dn }}
    attributes:
      uniqueMember:
        - "cn={{ item }},ou={{ ldap_ou_users }},ou={{ site_domain_ou }},{{ ldap_base_dn }}"
    server_uri: "{{ ldap_auth.server_uri }}"
    bind_dn: "{{ ldap_auth.bind_dn }}"
    bind_pw: "{{ ldap_auth.bind_pw }}"
  with_items: "{{ site_goun_nextcloud_users }}"
  tags:
    - ldap_goun

- name: Remove dummy member from group nextcloud
  community.general.ldap_attrs:
    dn: cn=nextcloud,ou={{ ldap_ou_goun }},{{ ldap_base_dn }}
    attributes:
      uniqueMember:
        - "cn=dummy,ou={{ ldap_ou_users }},ou={{ site_domain_ou }},{{ ldap_base_dn }}"
    state: absent
    server_uri: "{{ ldap_auth.server_uri }}"
    bind_dn: "{{ ldap_auth.bind_dn }}"
    bind_pw: "{{ ldap_auth.bind_pw }}"
  tags:
    - ldap_goun
